# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-01-31 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_clientuserprofile_user_and_more"),
        ("user", "0002_alter_user_client_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="client_profile",
        ),
        migrations.RemoveField(
            model_name="user",
            name="client_profile",
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organization.client",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organization.client",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organization.organization",
            ),
        ),
    ]
