# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-01-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
        ("user", "0002_historicaluser"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="customer_organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organization.customerorganization",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="customer_organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.customerorganization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
    ]
