# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_client_spv_password_client_spv_username_and_more"),
        ("user", "0003_remove_historicaluser_client_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organization.organization",
            ),
        ),
    ]
