# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-16 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("has_organization_admin", "Has organization Admin"),
                    ("has_settings_access", "Has access to settings"),
                    ("has_invoice_access", "Has access to client invoices"),
                    (
                        "has_client_general_information_costs_access",
                        "Has access to client general information",
                    ),
                    (
                        "has_client_activity_costs_access",
                        "Has access to client activities costs",
                    ),
                    ("has_client_add_access", "Has access to add clients"),
                ),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
