# -*- coding: utf-8 -*-
import graphene
from django.contrib.auth import get_user_model
from graphene_django import DjangoObjectType

from user.permissions import UserPermissionsEnum

UserModel = get_user_model()

UserPermissionsEnumType = graphene.Enum.from_enum(UserPermissionsEnum)


class UserType(DjangoObjectType):
    class Meta:
        model = UserModel
        only_fields = (
            "uuid",
            "email",
            "first_name",
            "last_name",
            "client_profile",
            "organization",
        )

    # Property
    name = graphene.String(required=True)

    client_profile = graphene.NonNull(
        "organization.graphene.types.ClientUserProfileType"
    )
    organization = graphene.NonNull("organization.graphene.types.OrganizationType")
    permissions = graphene.List(
        graphene.NonNull(UserPermissionsEnumType), required=True
    )

    def resolve_email(self, info):
        # If the email was generated by the system, pretend it doesn't exist
        if self.email == self.generate_client_user_email():
            return ""

        return self.email

    def resolve_permissions(self, info):
        return self.user_permissions.all().values_list("codename", flat=True)

    # START OF UNUSED FIELDS, BUT NEEDED ON THE FRONTEND
    photo_url = graphene.String(required=True)
    role = graphene.String(required=True)

    def resolve_photo_url(self, info):
        return ""

    def resolve_role(self, info):
        return ""

    # END OF UNUSED FIELDS
