# -*- coding: utf-8 -*-
from django.db import models

from core.models import BaseModel
from user.models import User


def report_path(instance, file_name):
    return "/".join(
        [
            "reports",
            str(instance.user.organization.id),
            str(instance.user.id),
            file_name,
        ]
    )


class UserReport(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    the_file = models.FileField(
        upload_to=report_path,
        help_text="Report generated by the user",
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"Report for {self.user.name}"

    def __repr__(self):
        return f"Report for {self.user.name}"

    @property
    def url(self):
        return self.the_file.url
