# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-01-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorganization",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_organizations",
                to="organization.organization",
            ),
        ),
    ]
