# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-01-31 08:17

import dirtyfields.dirtyfields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="accounting_app",
            field=models.CharField(
                blank=True,
                help_text="Application they use for accounting",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="inventory_app",
            field=models.CharField(
                blank=True,
                help_text="Application they use to manage inventory",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="accounting_app",
            field=models.CharField(
                blank=True,
                help_text="Application they use for accounting",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="inventory_app",
            field=models.CharField(
                blank=True,
                help_text="Application they use to manage inventory",
                max_length=128,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClientUserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "ownership_percentage",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="What percentage of the organization does this user own?",
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMINSTRATOR", "Adminstrator"),
                            ("ASSOCIATE", "Associate"),
                            ("EMPLOYEE", "Employee"),
                            ("MANAGER", "Manager"),
                        ],
                        help_text="Role in the organization",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "spv_username",
                    models.CharField(
                        blank=True, help_text="SPV Username", max_length=64, null=True
                    ),
                ),
                (
                    "spv_password",
                    models.CharField(
                        blank=True, help_text="SPV Password", max_length=64, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="organization.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalClientUserProfile",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "ownership_percentage",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="What percentage of the organization does this user own?",
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMINSTRATOR", "Adminstrator"),
                            ("ASSOCIATE", "Associate"),
                            ("EMPLOYEE", "Employee"),
                            ("MANAGER", "Manager"),
                        ],
                        help_text="Role in the organization",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "spv_username",
                    models.CharField(
                        blank=True, help_text="SPV Username", max_length=64, null=True
                    ),
                ),
                (
                    "spv_password",
                    models.CharField(
                        blank=True, help_text="SPV Password", max_length=64, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.client",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical client user profile",
                "verbose_name_plural": "historical client user profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
