# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-01-23 09:59

import dirtyfields.dirtyfields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_alter_customerorganization_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerorganization",
            name="monthly_invoice_ammount",
        ),
        migrations.RemoveField(
            model_name="customerorganization",
            name="monthly_invoice_currency",
        ),
        migrations.RemoveField(
            model_name="historicalcustomerorganization",
            name="monthly_invoice_ammount",
        ),
        migrations.RemoveField(
            model_name="historicalcustomerorganization",
            name="monthly_invoice_currency",
        ),
        migrations.AddField(
            model_name="customerorganization",
            name="phone_number_1",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="customerorganization",
            name="phone_number_2",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="historicalcustomerorganization",
            name="phone_number_1",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="historicalcustomerorganization",
            name="phone_number_2",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name="HistoricalInvoiceItem",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("description", models.TextField()),
                ("unit_price", models.IntegerField(blank=True, null=True)),
                (
                    "unit_price_currency",
                    models.CharField(
                        blank=True,
                        choices=[("RON", "Ron"), ("EUR", "Eur"), ("USD", "Usd")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "date_sent",
                    models.DateField(
                        blank=True,
                        help_text="Date when the invoice was sent to the customer",
                        null=True,
                    ),
                ),
                (
                    "minutes_allocated",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Number of minutes allocated to the customer for this invoice item",
                        null=True,
                    ),
                ),
                (
                    "is_fixed_cost",
                    models.BooleanField(
                        default=False,
                        help_text="Boolean indicating if this invoice item is a fixed cost or not. For example monthly recurring invoices are fixed",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "customer_organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.customerorganization",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical invoice item",
                "verbose_name_plural": "historical invoice items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("description", models.TextField()),
                ("unit_price", models.IntegerField(blank=True, null=True)),
                (
                    "unit_price_currency",
                    models.CharField(
                        blank=True,
                        choices=[("RON", "Ron"), ("EUR", "Eur"), ("USD", "Usd")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "date_sent",
                    models.DateField(
                        blank=True,
                        help_text="Date when the invoice was sent to the customer",
                        null=True,
                    ),
                ),
                (
                    "minutes_allocated",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Number of minutes allocated to the customer for this invoice item",
                        null=True,
                    ),
                ),
                (
                    "is_fixed_cost",
                    models.BooleanField(
                        default=False,
                        help_text="Boolean indicating if this invoice item is a fixed cost or not. For example monthly recurring invoices are fixed",
                    ),
                ),
                (
                    "customer_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_organization_invoice_items",
                        to="organization.customerorganization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
