# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-01-27 16:40

from django.db import migrations, models

import organization.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_customerorganization_cui_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorganizationdocument",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Document resource",
                null=True,
                upload_to=organization.models.document_path,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomerorganizationdocument",
            name="document",
            field=models.TextField(
                blank=True, help_text="Document resource", max_length=100, null=True
            ),
        ),
    ]
