# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-01 07:51

from django.db import migrations, models

import organization.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_clientuserprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="logo",
            field=models.TextField(
                blank=True, help_text="Organization logo", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Organization logo",
                null=True,
                upload_to=organization.models.organization_logo_path,
            ),
        ),
    ]
