# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_historicalorganization_logo_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="spv_password",
            field=models.CharField(
                blank=True, help_text="SPV Password", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="spv_username",
            field=models.CharField(
                blank=True, help_text="SPV Username", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="spv_password",
            field=models.CharField(
                blank=True, help_text="SPV Password", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="spv_username",
            field=models.CharField(
                blank=True, help_text="SPV Username", max_length=64, null=True
            ),
        ),
    ]
