# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-01-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_customerorganizationdocument_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorganizationdocument",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomerorganizationdocument",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
