# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_client_spv_password_client_spv_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuserprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="historicalclientuserprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
