# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-18 07:41

import dirtyfields.dirtyfields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_clientuserprofile_phone_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalinvoiceitem",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of the invoice item", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoiceitem",
            name="unit_price_type",
            field=models.CharField(
                blank=True,
                choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of the invoice item", max_length=256
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="unit_price_type",
            field=models.CharField(
                blank=True,
                choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoiceitem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional explanation for the invoice item",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoiceitem",
            name="unit_price",
            field=models.IntegerField(
                help_text="Price of the invoice item per unit type"
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoiceitem",
            name="unit_price_currency",
            field=models.CharField(
                choices=[("RON", "Ron"), ("EUR", "Eur"), ("USD", "Usd")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional explanation for the invoice item",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.IntegerField(
                help_text="Price of the invoice item per unit type"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price_currency",
            field=models.CharField(
                choices=[("RON", "Ron"), ("EUR", "Eur"), ("USD", "Usd")], max_length=3
            ),
        ),
        migrations.CreateModel(
            name="HistoricalStandardInvoiceItem",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Name of the invoice item", max_length=256
                    ),
                ),
                (
                    "unit_price",
                    models.IntegerField(
                        help_text="Price of the invoice item per unit type"
                    ),
                ),
                (
                    "unit_price_currency",
                    models.CharField(
                        choices=[("RON", "Ron"), ("EUR", "Eur"), ("USD", "Usd")],
                        max_length=3,
                    ),
                ),
                (
                    "unit_price_type",
                    models.CharField(
                        blank=True,
                        choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical standard invoice item",
                "verbose_name_plural": "historical standard invoice items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="StandardInvoiceItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Name of the invoice item", max_length=256
                    ),
                ),
                (
                    "unit_price",
                    models.IntegerField(
                        help_text="Price of the invoice item per unit type"
                    ),
                ),
                (
                    "unit_price_currency",
                    models.CharField(
                        choices=[("RON", "Ron"), ("EUR", "Eur"), ("USD", "Usd")],
                        max_length=3,
                    ),
                ),
                (
                    "unit_price_type",
                    models.CharField(
                        blank=True,
                        choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_invoice_items",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="historicalinvoiceitem",
            name="standard_invoice_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Connection to the initial standard invoice item. When provided, it copies the attributes from the standard invoice item.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organization.standardinvoiceitem",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="standard_invoice_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Connection to the initial standard invoice item. When provided, it copies the attributes from the standard invoice item.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="organization.standardinvoiceitem",
            ),
        ),
    ]
