# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0009_historicalinvoiceitem_quantity_invoiceitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinvoiceitem",
            name="unit_price_type",
            field=models.CharField(
                choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                help_text="The type of the invoice item can be fixed, per hour etc",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="historicalstandardinvoiceitem",
            name="unit_price_type",
            field=models.CharField(
                choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                help_text="The type of the invoice item can be fixed, per hour etc",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price_type",
            field=models.CharField(
                choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                help_text="The type of the invoice item can be fixed, per hour etc",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="standardinvoiceitem",
            name="unit_price_type",
            field=models.CharField(
                choices=[("FIXED", "Fixed"), ("HOURLY", "Hourly")],
                help_text="The type of the invoice item can be fixed, per hour etc",
                max_length=8,
            ),
        ),
    ]
