# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0011_standardinvoiceitemcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstandardinvoiceitemcategory",
            name="code",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="historicalstandardinvoiceitemcategory",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.standardinvoiceitemcategory",
            ),
        ),
        migrations.AlterField(
            model_name="standardinvoiceitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.standardinvoiceitemcategory",
            ),
        ),
    ]
