# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-02-28 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0012_alter_historicalstandardinvoiceitemcategory_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalinvoiceitem",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="organization",
        ),
    ]
