# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-11 07:58

import dirtyfields.dirtyfields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0014_activity_activitycategory_clientactivity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstandardinvoiceitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="historicalstandardinvoiceitem",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalstandardinvoiceitem",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="historicalstandardinvoiceitemcategory",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoiceitem",
            name="standard_invoice_item",
        ),
        migrations.RemoveField(
            model_name="standardinvoiceitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="standardinvoiceitem",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="clientsolution",
            name="month",
        ),
        migrations.RemoveField(
            model_name="clientsolution",
            name="year",
        ),
        migrations.RemoveField(
            model_name="historicalclientsolution",
            name="month",
        ),
        migrations.RemoveField(
            model_name="historicalclientsolution",
            name="year",
        ),
        migrations.CreateModel(
            name="ClientSolutionLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "minutes_allocated",
                    models.SmallIntegerField(
                        help_text="Number of minutes allocated to the client for this activity"
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when the activity was executed"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation for the log",
                        null=True,
                    ),
                ),
                (
                    "client_solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="organization.clientsolution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalClientSolutionLog",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "uuid",
                    models.CharField(
                        default=core.models.generate_uuid, editable=False, max_length=32
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                (
                    "deleted",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "minutes_allocated",
                    models.SmallIntegerField(
                        help_text="Number of minutes allocated to the client for this activity"
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date when the activity was executed"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation for the log",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "client_solution",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organization.clientsolution",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical client solution log",
                "verbose_name_plural": "historical client solution logs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="HistoricalInvoiceItem",
        ),
        migrations.DeleteModel(
            name="HistoricalStandardInvoiceItem",
        ),
        migrations.DeleteModel(
            name="HistoricalStandardInvoiceItemCategory",
        ),
        migrations.DeleteModel(
            name="InvoiceItem",
        ),
        migrations.DeleteModel(
            name="StandardInvoiceItemCategory",
        ),
        migrations.DeleteModel(
            name="StandardInvoiceItem",
        ),
    ]
