# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-09 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0014_activity_activitycategory_clientactivity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activity",
            name="organization_activity_name_client_category_unique",
        ),
    ]
