# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0014_activity_activitycategory_clientactivity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientsolution",
            options={"verbose_name_plural": "Client Activities"},
        ),
        migrations.AlterModelOptions(
            name="historicalclientsolution",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical client solution",
                "verbose_name_plural": "historical Client Activities",
            },
        ),
        migrations.AddConstraint(
            model_name="clientsolution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("month", "year", "client", "solution"),
                name="organization_client_activity_month_year_client_solution_unique",
            ),
        ),
    ]
