# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0015_remove_historicalstandardinvoiceitem_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitycategory",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="historicalactivitycategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical activity category",
                "verbose_name_plural": "historical Categories",
            },
        ),
        migrations.AlterField(
            model_name="clientactivitylog",
            name="minutes_allocated",
            field=models.SmallIntegerField(
                help_text="Number of minutes allocated for this activity"
            ),
        ),
        migrations.AlterField(
            model_name="clientsolutionlog",
            name="minutes_allocated",
            field=models.SmallIntegerField(
                help_text="Number of minutes allocated for this activity"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclientactivitylog",
            name="minutes_allocated",
            field=models.SmallIntegerField(
                help_text="Number of minutes allocated for this activity"
            ),
        ),
        migrations.AlterField(
            model_name="historicalclientsolutionlog",
            name="minutes_allocated",
            field=models.SmallIntegerField(
                help_text="Number of minutes allocated for this activity"
            ),
        ),
    ]
