# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0016_clientuserobjectpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientactivity",
            name="quantity",
            field=models.SmallIntegerField(
                default=1, help_text="Quantity of the Activity"
            ),
        ),
        migrations.AddField(
            model_name="clientsolution",
            name="quantity",
            field=models.SmallIntegerField(
                default=1, help_text="Quantity of the Activity"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientactivity",
            name="quantity",
            field=models.SmallIntegerField(
                default=1, help_text="Quantity of the Activity"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientsolution",
            name="quantity",
            field=models.SmallIntegerField(
                default=1, help_text="Quantity of the Activity"
            ),
        ),
    ]
