# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-29 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0019_clientgroup_client_group_historicalclient_group_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalActivityCategory",
            new_name="HistoricalOrganizationBusinessCategory",
        ),
        migrations.RenameModel(
            old_name="ActivityCategory",
            new_name="OrganizationBusinessCategory",
        ),
        migrations.AlterModelOptions(
            name="historicalorganizationbusinesscategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical organization business category",
                "verbose_name_plural": "historical Organization Business Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationbusinesscategory",
            options={"verbose_name_plural": "Organization Business Categories"},
        ),
        migrations.RemoveConstraint(
            model_name="organizationbusinesscategory",
            name="organization_activity_category_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="organizationbusinesscategory",
            name="organization_activity_category_code_unique",
        ),
        migrations.AlterField(
            model_name="clientsoftware",
            name="software",
            field=models.CharField(
                choices=[
                    ("ONE_C", "One C"),
                    ("SAGA", "Saga"),
                    ("NEXUS", "Nexus"),
                    ("TEAMAPP", "Teamapp"),
                    ("NEXTUP", "Nextup"),
                    ("WIND", "Wind"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclientsoftware",
            name="software",
            field=models.CharField(
                choices=[
                    ("ONE_C", "One C"),
                    ("SAGA", "Saga"),
                    ("NEXUS", "Nexus"),
                    ("TEAMAPP", "Teamapp"),
                    ("NEXTUP", "Nextup"),
                    ("WIND", "Wind"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationbusinesscategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("name",),
                name="organization_organization_business_category_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationbusinesscategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("code",),
                name="organization_organization_business_category_code_unique",
            ),
        ),
    ]
