# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0020_rename_historicalactivitycategory_historicalorganizationbusinesscategory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="categories",
            field=models.ManyToManyField(
                related_name="organizations",
                to="organization.organizationbusinesscategory",
            ),
        ),
    ]
