# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-03-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0022_categoryuserobjectpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuserprofile",
            name="show_in_group",
            field=models.BooleanField(
                default=False,
                help_text="If true, the user will show for all clients in the same group",
            ),
        ),
        migrations.AddField(
            model_name="historicalclientuserprofile",
            name="show_in_group",
            field=models.BooleanField(
                default=False,
                help_text="If true, the user will show for all clients in the same group",
            ),
        ),
    ]
