# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0024_alter_clientsoftware_software_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientactivity",
            name="is_recurrent",
            field=models.BooleanField(
                default=False, help_text="Is the activity recurrent?"
            ),
        ),
        migrations.AddField(
            model_name="historicalclientactivity",
            name="is_recurrent",
            field=models.BooleanField(
                default=False, help_text="Is the activity recurrent?"
            ),
        ),
        migrations.AlterField(
            model_name="clientsoftware",
            name="software",
            field=models.CharField(
                choices=[
                    ("FGO", "Fgo"),
                    ("NEOMANAGER", "Neomanager"),
                    ("NEXTUP", "Nextup"),
                    ("NEXUS", "Nexus"),
                    ("OBLIO", "Oblio"),
                    ("ONE_C", "One C"),
                    ("ONE_C_ALIN", "One C Alin"),
                    ("REGES", "Reges"),
                    ("SAGA", "Saga"),
                    ("SENIOR_ERP", "Senior Erp"),
                    ("SENIOR_ERP_CLIENT", "Senior Erp Client"),
                    ("SICO_FINANCIAR", "Sico Financiar"),
                    ("SICO_GESTIUNI", "Sico Gestiuni"),
                    ("SMARTBILL", "Smartbill"),
                    ("TEAMAPP", "Teamapp"),
                    ("WIND", "Wind"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclientsoftware",
            name="software",
            field=models.CharField(
                choices=[
                    ("FGO", "Fgo"),
                    ("NEOMANAGER", "Neomanager"),
                    ("NEXTUP", "Nextup"),
                    ("NEXUS", "Nexus"),
                    ("OBLIO", "Oblio"),
                    ("ONE_C", "One C"),
                    ("ONE_C_ALIN", "One C Alin"),
                    ("REGES", "Reges"),
                    ("SAGA", "Saga"),
                    ("SENIOR_ERP", "Senior Erp"),
                    ("SENIOR_ERP_CLIENT", "Senior Erp Client"),
                    ("SICO_FINANCIAR", "Sico Financiar"),
                    ("SICO_GESTIUNI", "Sico Gestiuni"),
                    ("SMARTBILL", "Smartbill"),
                    ("TEAMAPP", "Teamapp"),
                    ("WIND", "Wind"),
                ],
                max_length=32,
            ),
        ),
    ]
