# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-06-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0026_alter_clientsoftware_software_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientsolution",
            name="unit_cost",
            field=models.IntegerField(
                help_text="Cost/Price of the Solution", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalclientsolution",
            name="unit_cost",
            field=models.IntegerField(
                help_text="Cost/Price of the Solution", null=True
            ),
        ),
    ]
