# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-06-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0026_alter_clientsoftware_software_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuserprofile",
            name="spv_email",
            field=models.EmailField(
                blank=True, help_text="SPV Email", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalclientuserprofile",
            name="spv_email",
            field=models.EmailField(
                blank=True, help_text="SPV Email", max_length=254, null=True
            ),
        ),
    ]
