# -*- coding: utf-8 -*-
# Generated by Django 5.0.1 on 2024-12-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0027_clientuserprofile_spv_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientfile",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("OPCSB", "Opcsb")],
                help_text="FIle Type. If not specified, it's a general file",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclientfile",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("OPCSB", "Opcsb")],
                help_text="FIle Type. If not specified, it's a general file",
                max_length=64,
                null=True,
            ),
        ),
    ]
